version: '3.7'

x-environemnt:
  DATABASE: postgres
  SQL_DATABASE: postgres
  SQL_HOST: db
  SQL_PASSWORD: postgres
  SQL_PORT: '5432'
  SQL_USER: postgres

services:
  db:
    image: postgres:10.5-alpine
    restart: always
    ports:
      - 5431:5432
    volumes:
      - ./database/scripts:/scripts
      - ./database/target/postgres_data:/var/lib/postgresql/data

